### ISSUE TITLE
Ability to turn on/off the "Try it out" functionality 

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#191]
Sometimes Stoplight users don't want to show the "Try it out" feature. It would be nice to have the ability to turn it off.

**Comment by marbemac** [comment]
This can be done with some simple css - perhaps we should add it to the documentation?

```css
.ApiOperation--tryItOutTitle {
  display: none;
}
```
